### PR TITLE
Change translate in nuget-config-file.md

### PR DESCRIPTION
**Pull request by blacksnake-rus**

### CODE REVIEW

**Comment by srvbpigh** [comment]
Здравствуйте, @blacksnake-rus.

Спасибо за Ваше предложение! Сейчас мы рассматриваем его и скоро сообщим Вам о результатах.  


С наилучшими пожеланиями, 

Microsoft DOCS Global Experience Team

**Comment by srvbpigh** [comment]
Здравствуйте, @blacksnake-rus:

Спасибо за Ваше предложение! Ваши правки были частично приняты. Мы выполним слияние Вашего PR, но также зафиксируем новый PR для отмены отклоненных изменений. Принятые правки будут использованы в следующей версии статьи. Комментарии по отклоненным правкам приведены ниже.

----------------------------º---------------------------- 
 **docs/reference/nuget-config-file.md** 

**Текущая версия:** 
```
## <a name="package-source-sections"></a>Разделы источников пакета
```

**Запрос на изменение:** 
```
## <a name="package-source-sections"></a>Разделы packageSources
```
**Причина отклонения:** Does not follow the original EN page.
----------------------------º---------------------------- 



С наилучшими пожеланиями,

Microsoft DOCS Global Experience Team

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by blacksnake-rus** [comment]
> Здравствуйте, @blacksnake-rus:
> 
> Спасибо за Ваше предложение! Ваши правки были частично приняты. Мы выполним слияние Вашего PR, но также зафиксируем новый PR для отмены отклоненных изменений. Принятые правки будут использованы в следующей версии статьи. Комментарии по отклоненным правкам приведены ниже.
> 
> ----------------------------º----------------------------
> **docs/reference/nuget-config-file.md**
> 
> **Текущая версия:**
> 
> ```
> ## <a name="package-source-sections"></a>Разделы источников пакета
> ```
> 
> **Запрос на изменение:**
> 
> ```
> ## <a name="package-source-sections"></a>Разделы packageSources
> ```
> 
> **Причина отклонения:** Does not follow the original EN page.
> ----------------------------º----------------------------
> 
> С наилучшими пожеланиями,
> 
> Microsoft DOCS Global Experience Team

I do not agree with you

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Pull request merged**
