### PR TITLE
Test PR

### PR DESCRIPTION
**Pull request by sacor**

### CODE REVIEW

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by srvbpigh** [comment]
Здравствуйте, @sacor.

Спасибо за Ваше предложение! Сейчас мы рассматриваем его и скоро сообщим Вам о результатах.  


С наилучшими пожеланиями, 

Microsoft DOCS Global Experience Team

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Pull request closed without merging**
